---
title: "Initial Forest Farming Stats"
author: "VB"
date: "2024-08-27"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read excel, echo = FALSE}
library(readxl)
Summer_24 <- read_excel("~/Downloads/Summer'24 (1).xlsx", 
    sheet = "Light&Soil")
characteristics <- read_excel("~/Downloads/Summer'24 (1).xlsx", 
    sheet = "Characteristics&Growth for R")
mortality <- read_excel("~/Downloads/Summer'24 (1).xlsx", 
    sheet = "Mortality")
randomized_planting <- read_excel("~/Downloads/randomized_planting_part1.xlsx")
```


```{r library, echo = FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(tidymodels)
library(scatterplot3d)
library(wesanderson)
```

```{r summary, echo = FALSE}
Summer_24 %>% 
  group_by(D) %>% 
  summarize(mean_moisture = mean(soil_moisture), 
            median_moisture = median(soil_moisture),
            sd_moisture = sd(soil_moisture),
            min_soil_moisture = min(soil_moisture, na.rm = TRUE),
    max_soil_moisture = max(soil_moisture, na.rm = TRUE))


Summer_24 %>% 
  group_by(microclimate_id) %>% 
  summarize(mean_moisture = mean(soil_moisture), 
            median_moisture = median(soil_moisture),
            sd_moisture = sd(soil_moisture),
            min_soil_moisture = min(soil_moisture, na.rm = TRUE),
    max_soil_moisture = max(soil_moisture, na.rm = TRUE))


```
## Soil Moisture Boxplots
```{r boxplots}
ggplot(Summer_24, aes(x = factor(D), y = soil_moisture)) +
  geom_boxplot() +
  labs(x = "D Value", y = "Soil Moisture") +
  theme_minimal()

ggplot(Summer_24, aes(x = factor(microclimate_id), y = soil_moisture)) +
  geom_boxplot() +
  labs(x = "Microclimate", y = "Soil Moisture") +
  theme_minimal()

```
North Forest: D1-D6
Northern Edge: D7
Clear Cut: D8-D12
Southern Edge: D13
South Forest: D14-D18

```{r scatter, echo = FALSE}

##this means absolutely nothing until we have more light data and 
##even then may not be useful for our purposes 
#Summer_24 %>%
 # filter(!is.na(light_conditions)) %>%
#ggplot(aes(x = light_conditions, y = soil_moisture)) +
 # geom_point() +
 # labs(x = "Light Conditions", y = "Moisture") +
 # theme_minimal()

```
```{r mortality summary, echo = FALSE}

#dead_NW <- sum(mortality$NW == 0)
#dead_NE <- sum(mortality$NE == 0)
#dead_SW <- sum(mortality$SW == 0)
#dead_SE <- sum(mortality$SE == 0)


#live_NW <- sum(mortality$NW == 1)
#live_NE <- sum(mortality$NE == 1)
#live_SW <- sum(mortality$SW == 1)
#live_SE <- sum(mortality$SE == 1)

```

```{r count 1, echo = FALSE}

#dead <- sapply(mortality, function(x) sum(x == 0))
#alive <- sapply(mortality, function(x) sum(x == 1))

#result_table <- data.frame(
 # Variable = names(mortality),
 # dead = count_zeros,
 # alive = count_ones)

#mortality_relevant <- result_table[-c(1, 2, 3, 4, 5, 10), ]

#mortality_relevant %>%
 # bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))
```

```{r join and pivot}
sum_24_red_for_mortality <- Summer_24 %>% slice(1:432)
combined_characteristics_loc <- full_join(sum_24_red_for_mortality, mortality,
                                          by = "plot")

plants_long <- combined_characteristics_loc %>%
  pivot_longer(cols = c(NW, NE, SW, SE), 
               names_to = "direction", 
               values_to = "mortality")

```

## Mortality by Microclimate
```{r mortality by microclimate}
plants_long %>%
  group_by(microclimate_id) %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))


mortality_plot_data <- plants_long %>%
  group_by(microclimate_id, mortality) %>%
  summarise(count = n()) %>%
  ungroup()

ggplot(mortality_plot_data, 
       aes(x = microclimate_id, y = count, fill = factor(mortality))) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Microclimate", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Microclimate")
```

## Mortality by Treatment Type 

```{r mortality by treatment}
FULL <- full_join(plants_long, randomized_planting, 
                                 by = "plot")

FULL %>%
  group_by(treatment) %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))

mortality_by_treatment <- FULL %>%
  group_by(treatment, mortality) %>%
  summarise(count = n()) %>%
  ungroup()

mortality_by_treatment$treatment <- factor(mortality_by_treatment$treatment, levels = 1:12)

ggplot(mortality_by_treatment, 
       aes(x = treatment, y = count, fill = factor(mortality))) +
  geom_col(width=0.5,    
           position=position_dodge(0.5)) +
  labs(x = "Treatment ID", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Treatment Type")
```
```{r mutate}
FULL <- FULL %>%
  mutate(plant = case_when(
    treatment == 1 ~ "goldenseal",
    treatment == 2 ~ "ginseng",
    treatment == 3 & (direction == "NE" | direction == "SW") ~ "goldenseal",
    treatment == 3 & (direction == "NW" | direction == "SE") ~ "ginseng",
    treatment == 4 & (direction == "NE" | direction == "SW") ~ "goldenseal",
    treatment == 4 & (direction == "NW" | direction == "SE") ~ "strawberry",
    treatment == 5 & (direction == "NE" | direction == "SW") ~ "ginseng",
    treatment == 5 & (direction == "NW" | direction == "SE") ~ "strawberry",
    treatment == 6 & (direction == "NW" | direction == "SE") ~ "strawberry", 
    treatment == 6 & (direction == "NE") ~ "goldenseal", 
    treatment == 6 & (direction == "SW") ~ "ginseng", 
    treatment == 7 & (direction == "NE" | direction == "SW") ~ "goldenseal", 
    treatment == 7 & (direction == "NW" | direction == "SE") ~ "clover", 
    treatment == 8 & (direction == "NE" | direction == "SW") ~ "ginseng", 
    treatment == 8 & (direction == "NW" | direction == "SE") ~ "clover", 
    treatment == 9 & (direction == "NW" | direction == "SE") ~ "ginseng", 
    treatment == 9 & (direction =="NE") ~ "goldenseal", 
    treatment == 9 & (direction == "SW") ~ "ginseng", 
    treatment == 10 & (direction == "NE" | direction == "SW") ~ "goldenseal", 
    treatment == 10 & (direction == "NW") ~ "strawberry", 
    treatment == 10 & (direction == "SE") ~ "white clover", 
    treatment == 11 & (direction == "NE" | direction == "SW") ~ "ginseng", 
    treatment == 11 & (direction == "NW") ~ "strawberry", 
    treatment == 11 & (direction == "SE") ~ "clover", 
    treatment == 12 & (direction == "NE") ~ "ginseng", 
    treatment == 12 & (direction == "SE") ~ "clover", 
    treatment == 12 & (direction == "SW") ~ "goldenseal", 
    treatment == 12 & (direction == "NW") ~ "strawberry"))
```

## Mortality by Plant Species
```{r mortality by plant}
FULL %>%
  group_by(plant) %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))

mortality_by_plant <- FULL %>%
  group_by(plant, mortality) %>%
  summarise(count = n()) %>%
  ungroup()

#mortality_by_plant$plant <- factor(mortality_by_plant$plant, levels = 1:12)

ggplot(mortality_by_plant, 
       aes(x = plant, y = count, fill = factor(mortality))) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Species", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Species")
```

```{r mortality by species in clear cut}
FULL %>%
  group_by(plant) %>%
  filter(microclimate_id == "Clear Cut") %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))

mortality_by_plant_cc <- FULL %>%
  filter(microclimate_id == "Clear Cut") %>%
  group_by(plant, mortality) %>%
  summarise(count = n()) %>%
  ungroup()
  
ggplot(mortality_by_plant_cc, 
       aes(x = plant, y = count, fill = factor(mortality))) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Species", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Species in the Clear Cut")  

```
```{r forest mortality}
FULL %>%
  group_by(plant) %>%
  filter(microclimate_id == "North Forest" | 
           microclimate_id == "South Forest") %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))

mortality_by_plant_forest <- FULL %>%
  filter(microclimate_id == "North Forest" | 
           microclimate_id == "South Forest") %>%
  group_by(plant, mortality) %>%
  summarise(count = n()) %>%
  ungroup()
  
ggplot(mortality_by_plant_forest, 
       aes(x = plant, y = count, fill = factor(mortality))) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Species", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Species in the forest")  
```
```{r edge mortality}
FULL %>%
  group_by(plant) %>%
  filter(microclimate_id == "Northern Edge" | 
           microclimate_id == "Southern Edge") %>%
  summarise(total_plants = n(),
            dead_plants = sum(mortality == 0),
            live_plants = sum(mortality == 1),
            mortality_rate = dead_plants / total_plants) %>% 
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total"))

mortality_by_plant_edges <- FULL %>%
  filter(microclimate_id == "Northern Edge" | 
           microclimate_id == "Southern Edge") %>%
  group_by(plant, mortality) %>%
  summarise(count = n()) %>%
  ungroup()
  
ggplot(mortality_by_plant_edges, 
       aes(x = plant, y = count, fill = factor(mortality))) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Species", y = "Count of Plants", fill = "Mortality Status") +
  scale_fill_manual(values = c("0" = "tomato", "1" = "seagreen"), 
                    labels = c("Dead", "Live")) +
  theme_minimal() +
  ggtitle("Plant Mortality by Species in Edge Microclimates")
```

